server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.79.50:3306/dbBR?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
        username: latdbdev
        password: l@tThe0ne
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.betmatrix.theonex.dao.br.model

logging:
  level:
    Root: info
    org: info
    com: debug
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

