spring:
  cache:
    ehcache:
      config: classpath:ehcache.xml
logging:
  level:
    root: info
    org:
      springframework:
        cache: debug
    net:
      sf:
        ehcache: debug

debug: true
server:
  port: 8080

